### ISSUE TITLE
Not Working on 1.8.8

### ISSUE THREAD

**Issue by Vennntox** [OnlyNoobDied/GadgetsMenu#251]
17:19:39 [SEVERE] Could not load 'plugins\GadgetsMenu.jar' in folder 'plugins'
17:19:39 org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldguard/session/handler/Handler$Factory
17:19:39 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:39 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:39 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
17:19:40 Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/session/handler/Handler$Factory
17:19:40 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
17:19:40 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
17:19:40 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	... 6 more
17:19:40 Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.session.handler.Handler$Factory
17:19:40 	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
17:19:40 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
17:19:40 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
17:19:40 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
17:19:40 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
17:19:40 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
17:19:40 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]

**Comment by OnlyNoobDied** [comment]
This issue is cause by outdated worldguard. I will fix this tomorrow.

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
