### ISSUE TITLE
Task #36452 for GadgetsMenu v4.5.10 generated an exception

### ISSUE THREAD

**Issue by HexonCz** [OnlyNoobDied/GadgetsMenu#748]
The Morph feature worked great at 1.14.4 but when I updated the server to 1.15.2 this error started showing in the console when trying to Morph...

**ERROR in the console:**
```
[GadgetsMenu] Task #36452 for GadgetsMenu v4.5.10 generated an exception
java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.MobDisguise.setShowName(Z)Lme/libraryaddict/disguise/disguisetypes/Disguise;
at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.disguise(LibDisguise.java:44) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphType.equip(MorphType.java:291) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:670) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$36(PlayerManager.java:1124) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[21:09:20] [Server thread/INFO]: [RewardPRO] eu.superm.minecraft.rewardpro.c.a: Player already joined today.'
[21:35:43] [Server thread/INFO]: [ProtocolLib] The updater found an update, and has readied it to be loaded the next time the server restarts/reloads.
[21:36:17] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v4.5.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.MobDisguise.setShowName(Z)Lme/libraryaddict/disguise/disguisetypes/Disguise;
at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.disguise(LibDisguise.java:44) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphType.equip(MorphType.java:291) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:670) ~[?:?]
at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:236) ~[?:?]
at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-800b93f-8160e29]
... 17 more
[21:36:35] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v4.5.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.MobDisguise.setShowName(Z)Lme/libraryaddict/disguise/disguisetypes/Disguise;
at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.disguise(LibDisguise.java:44) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphType.equip(MorphType.java:291) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:670) ~[?:?]
at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:236) ~[?:?]
at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-800b93f-8160e29]
```

**Steps to reproduce the behavior:**
1. Open Morph Menu
2. Click on whatever morph option
3. See error

**Server info:**
 - Server Version: 1.15.2
 - GadgetsMenu Version: 4.5.10

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
